version: "3.8"

services:
  github-runner:
    build:
      context: .
    container_name: github-runner
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_NAME: ${RUNNER_NAME}
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
    restart: unless-stopped
    volumes:
      - runner-data:/actions-runner
volumes:
  runner-data:
