version: "3.8"

services:
  github-runner:
    build:
      context: .
    container_name: github-runner
    environment:
      REPO_URL_FE: ${REPO_URL}
      RUNNER_NAME_FE: ${RUNNER_NAME}
      GITHUB_RUNNER_TOKEN_FE: ${GITHUB_RUNNER_TOKEN}
    restart: unless-stopped
    volumes:
      - runner-data:/actions-runner
